services:
  ms-usuarios:
    build: ./ms-usuarios
    container_name: cnt-ms-usuarios
    ports:
      - "8080:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://cnt-db-rednorte:3306/db_usuarios
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=11223344
    depends_on:
      db-rednorte:
        condition: service_healthy
  ms-reasignacion:
    build: ./ms-reasignacion
    container_name: cnt-ms-reasignacion
    ports:
      - "8082:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://cnt-db-rednorte:3306/db_reasignacion
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=11223344
    depends_on:
      db-rednorte:
        condition: service_healthy
  db-rednorte:
    image: mysql:8.4
    container_name: cnt-db-rednorte
    environment:
      - MYSQL_ROOT_PASSWORD=11223344
    ports:
      - "3307:3306"
    volumes:
      - vol_usuarios_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p11223344"]
      interval: 10s
      retries: 5
volumes:
  vol_usuarios_data: